### ISSUE TITLE
Tasks in "Board" layout aren't coloured correctly

### ISSUE THREAD

**Issue by PrimedPixel** [dracula/todoist#3]
As the title says, the "cards" in the board layout retain the default colours. See image below.

![image](https://github.com/dracula/todoist/assets/83833773/a1b4a8fa-5b66-4214-8dbb-e0232b62b9a3)

**Comment by SIMULATAN** [comment]
![image](https://github.com/dracula/todoist/assets/63104422/0bb2e3e6-e7dd-450e-9cd1-18fe6858fd98)

Thanks for reporting, should be fixed in v2.0.1
